name: Test
on: ["pull_request", "push"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12]
        poetry-version: [1.8.3]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python and Poetry
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: ${{matrix.python-version}}
          poetry-version: ${{matrix.poetry-version}}
      - name: Run tests
        run: poetry run pytest
